package com.plyblox.proxychat.utility.config;

public enum ConfigDataKey {

    BOT_TOKEN,
    PREFIX,
    SERVERS,
    JOIN_FORMAT,
    LEAVE_FORMAT,
    MESSAGE_FORMAT,
    SWITCH_FORMAT,
    SWITCH_FORMAT_NO_FROM,

    MINECRAFT_TO_DISCORD_JOIN,
    MINECRAFT_TO_DISCORD_LEAVE,
    MINECRAFT_TO_DISCORD_SWITCH,

    DISCORD_TO_MINECRAFT_MESSAGE

}
