version: 2
updates:
  - package-ecosystem: "gradle"
    directories:
      - ""
      - "projects/common"
      - "projects/proxy"
      - "projects/proxy/shared"
      - "projects/proxy/velocity"
      - "projects/proxy/bungeecord"
      - "projects/server"
      - "projects/server/shared"
      - "projects/server/spigot"
    target-branch: "master"
    schedule:
      interval: "daily"
    commit-message:
      prefix: fix
      prefix-development: fix
      include: scope
