# ==========================================================
#                       INFORMATION
#                 HEX Values are Supported
#  Example: <#FFFFFF>Some text</#FFFFFF> this is a message!
#         Supports Mini-Message/Legacy Color Codes
# ==========================================================

# True if you will be using Discord. The reload command does not work with this.
use-discord: false

# Discord Bot Token (IGNORE IF use_discord = false). The reload command does not work with this.
BOT-TOKEN: "TOKEN_HERE"

# Channel to send Discord messages to (IGNORE IF use_discord = false). The reload command does not work with this.
CHANNEL-ID: "GLOBAL_CHANNEL_ID"

# The amount of seconds to check if a server is online/offline.
# Smaller numbers can cause errors. Beware.
server-update-interval: 3

# Use this if you want to change the default aliases.
# It MUST be the same name you have in your bungee/velocity config.
# Simply set it to disabled: disabled to disable it.
aliases:
  ServerInConfigExample: ServerAliasExample
  hub: Hub1
  smp: smp1

# Whether to use the permission system.
# simpleproxy.read.join - Read join messages.
# simpleproxy.read.leave - Read leave messages.
# simpleproxy.read.switch - Read switch messages.
# simpleproxychat.reload - ALWAYS Active whether use-permissions is false or not.
use-permissions: false

# Whether to send if the statuses of the servers connected to the proxy when the proxy starts up.
# THIS IS FOR DISCORD MESSAGES ONLY.
use-initial-server-status: true

# DO NOT TOUCH THIS
file-version: 6
