name: Add Labels to PR

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize ]
    branches-ignore: [ 'release-please**', 'dependabot/**' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  remove-labels:
    if: ${{ !startsWith(github.head_ref, 'dependabot/') && !startsWith(github.head_ref, 'release-please') }}
    name: Remove Labels
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      -
        name: Get Current Labels
        id: get_labels
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            const labels = pullRequest.labels.map(label => label.name);
            core.setOutput('labels', JSON.stringify(labels));
      -
        name: Remove All Labels
        uses: actions/github-script@v7
        with:
          script: |
            const labelsToRemove = JSON.parse(process.env.LABELS_TO_REMOVE);
            if (labelsToRemove.length > 0) {
              await github.rest.issues.removeAllLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
              });
              console.log(`Removed all labels from PR #${context.payload.pull_request.number}`);
            } else {
              console.log(`No labels to remove from PR #${context.payload.pull_request.number}`);
            }
        env:
          LABELS_TO_REMOVE: ${{ steps.get_labels.outputs.labels }}

  labeler:
    if: ${{ !startsWith(github.head_ref, 'dependabot/') && !startsWith(github.head_ref, 'release-please') }}
    name: Label PR
    permissions:
      pull-requests: write
      contents: read
      issues: write
    runs-on: ubuntu-latest
    needs: [ remove-labels ]
    steps:
      -
        uses: codelytv/pr-size-labeler@v1
        with:
          xs_label: 'size/xs'
          xs_max_size: '10'
          s_label: 'size/s'
          s_max_size: '100'
          m_label: 'size/m'
          m_max_size: '500'
          l_label: 'size/l'
          l_max_size: '1000'
          xl_label: 'size/xl'
          fail_if_xl: 'false'
          message_if_xl: >
            This PR exceeds the recommended size of 1000 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
            Note this PR might be rejected due to its size.
          github_api_url: 'https://api.github.com'
          files_to_ignore: |
            "package-lock.json"
            "*.lock"
            "docs/*"
